### ISSUE TITLE
Autotools 

### ISSUE THREAD

**Issue by skroo** [Kerwood/Rtorrent-LXC#2]
Thank you for this.

For some reason, I can't get Autotools working on a file copy. I'm new to docker, so I'm not sure where log files might live so I can check those. I've tried mounting an additional directory inside my start script, as well as just making a sub directory inside the /downloads mount point. I'm kind of thinking maybe it's just a perms problem or something, but the docker engine appears to run as root so I'm stumped. I'm starting the container based on your example command.

```
#!/bin/bash

docker run --name rtorrent \
    -v /home/me/Downloads:/downloads \
    -e HTUSER=me \
    -e HTPASS=password \
    -p 8181:80 \
    -p 51001:51001 \
    -d kerwood/rtorrent-lxc
```

My goal is to get completed torrents copied in a directory, different from downloads, that syncs with btsync.

**Comment by skroo** [comment]
This was a permission problem.

Rtorrent is running as "me" as far as the host system permissions are concerned, so the directory to be synced needs to be set to "me." The owner of my sync directory was btsync:btsync, and it needed to be me:bytsync.

Again, thanks for this container.

**Comment by Kerwood** [comment]
Good you figured it out :)
